apiVersion: v1
kind: Service
metadata:
  name: mysql-1
spec:
  ports:
  - port: 3306
  selector:
    app: mysql-1
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-1
spec:
  selector:
    matchLabels:
      app: mysql-1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-1
    spec:
      containers:
      - image: mysql:8.0
        name: mysql-1
        env:
        - name: MYSQL_USER
          value: petclinic
        - name: MYSQL_PASSWORD
          value: petclinic
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: petclinic
        ports:
        - containerPort: 3306
          name: mysql-1
        volumeMounts:
        - name: mysql-1-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-1-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-1-pv-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-1-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-1-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi